# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a92fdbb2c0e6abf66e6e9f6b532617eb771680fe60ec766c164ee9ed9ea888bdfb02c0764a7a5b96e0835093fb0fb3fd47f2fe1af97397490d2e4a5ac2ccf007

test:
  secret_key_base: f2a650dfdb6a17d14f6728feb144f7f4c34ee938f57acd9ee5f66831b64860507943eac2cbc5f6c9f9352bad73ac36d99ee38497a7539b3a7c7a3c3b845136b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
